"""Update Payment model to include additional details

Revision ID: 376ef8c9d2bc
Revises: 2137b948453b
Create Date: 2024-07-25 10:38:19.900540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376ef8c9d2bc'
down_revision = '2137b948453b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('nssf', sa.Float(), nullable=False),
    sa.Column('employer_nssf', sa.Float(), nullable=False),
    sa.Column('paye', sa.Float(), nullable=False),
    sa.Column('tin_number', sa.String(length=100), nullable=False),
    sa.Column('nssf_number', sa.String(length=100), nullable=False),
    sa.Column('preferred_payment_mode', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
