"""Added allowances and benefits fields to Employee model

Revision ID: 39744014a76e
Revises: 0d46617c269f
Create Date: 2024-08-21 19:14:07.061813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39744014a76e'
down_revision = '0d46617c269f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('housing_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('medical_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leave_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('housing_benefit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('motor_vehicle_benefit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('domestic_servant_benefit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_benefit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('other_benefit')
        batch_op.drop_column('domestic_servant_benefit')
        batch_op.drop_column('motor_vehicle_benefit')
        batch_op.drop_column('housing_benefit')
        batch_op.drop_column('other_allowance')
        batch_op.drop_column('overtime_allowance')
        batch_op.drop_column('leave_allowance')
        batch_op.drop_column('medical_allowance')
        batch_op.drop_column('transport_allowance')
        batch_op.drop_column('housing_allowance')

    # ### end Alembic commands ###
