"""Initial migration

Revision ID: d0ac1771eaa8
Revises: 
Create Date: 2024-07-01 15:25:19.052828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ac1771eaa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('tin_number', sa.String(length=100), nullable=False),
    sa.Column('nssf_number', sa.String(length=100), nullable=False),
    sa.Column('preferred_payment_mode', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
