"""Add resident status and work permit fields to Employee

Revision ID: d887cbce3599
Revises: 39744014a76e
Create Date: 2024-08-21 20:53:46.696190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd887cbce3599'
down_revision = '39744014a76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resident_status', sa.String(length=20), nullable=False,server_default='Resident'))
        batch_op.add_column(sa.Column('work_permit_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('work_permit_number')
        batch_op.drop_column('resident_status')

    # ### end Alembic commands ###
